import { useState, useRef } from 'react'

export function UploadSection({ onUploadSuccess }) {
  const [uploadStatus, setUploadStatus] = useState('')
  const [statusClass, setStatusClass] = useState('')
  const [dragover, setDragover] = useState(false)
  const fileInputRef = useRef(null)

  const handleFile = async (file) => {
    if (!file || file.type !== 'application/pdf') {
      setUploadStatus('Please select a valid PDF file.')
      setStatusClass('error')
      return
    }

    setUploadStatus('Extracting text...')
    setStatusClass('')

    try {
      const arrayBuffer = await file.arrayBuffer()
      const parsed = await onUploadSuccess(arrayBuffer)
      if (parsed) {
        setUploadStatus('Form filled. You can edit and regenerate the PDF.')
        setStatusClass('success')
      }
    } catch (err) {
      console.error('PDF parse error:', err)
      setUploadStatus('Could not parse PDF. Try a planner PDF generated by this app.')
      setStatusClass('error')
    }
  }

  const handleInputChange = (e) => {
    const file = e.target.files?.[0]
    if (file) handleFile(file)
    e.target.value = ''
  }

  const handleDrop = (e) => {
    e.preventDefault()
    setDragover(false)
    const file = e.dataTransfer?.files?.[0]
    if (file) handleFile(file)
  }

  return (
    <section className="card upload-card">
      <h2>Edit Existing Planner</h2>
      <p className="upload-desc">Upload a planner PDF (generated by this app) to extract and edit its content.</p>
      <div
        className={`upload-zone ${dragover ? 'dragover' : ''}`}
        id="upload-zone"
        onClick={() => fileInputRef.current?.click()}
        onDragOver={(e) => { e.preventDefault(); setDragover(true) }}
        onDragLeave={() => setDragover(false)}
        onDrop={handleDrop}
      >
        <input
          ref={fileInputRef}
          type="file"
          id="pdf-input"
          accept=".pdf"
          hidden
          onChange={handleInputChange}
        />
        <div className="upload-content" id="upload-content">
          <span className="upload-icon">📄</span>
          <p>Drop your PDF here or <strong>click to browse</strong></p>
        </div>
      </div>
      <p className={`upload-status ${statusClass}`} aria-live="polite">{uploadStatus}</p>
    </section>
  )
}
